#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 4
bspc config window_gap 12

#bspc config normal_border_color '#cccccc'
bspc config focused_border_color '#a01188'

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#Autostart applicatios
sxhkd &
picom --config ~/.config/picom/picom.conf &
~/.fehbg &
dunst &
polybar &

#For Touchpad
xinput set-prop 12 "libinput Tapping Enabled" 1
