#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 3
bspc config window_gap 18

#bspc config normal_border_color '#cccccc'
# bspc config focused_border_color '#a01188'
bspc config focused_border_color '#bd5eff'

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a blueberry state=floating
bspc rule -a Network state=floating

#Autostart applicatios
sxhkd &
picom --config ~/.config/picom/picom.conf &
~/.fehbg &
dunst &
polybar &

#For Touchpad
xinput set-prop 12 "libinput Tapping Enabled" 1
